server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimeZone=UTF&characterEncoding=UTF8
    username: username
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fisherman.model
